return { t = {}, p = {} }
local whitelist = {
  t = {
    ["LQh2i9"] = "2026-02-05 0:0:0",
    ["4jbUMw"] = "2026-02-24 0:0:0",
    ["4t9J5I"] = "2026-1-16 0:0:0",
    ["GpXB7L"] = "2026-1-23 0:0:0",
  },
  p = {
    "MkCMxW",
    "LQ4hPt",
    "Tq9LGK",
    "B6cPAt",
    "m88AUI",
    "H5dHjN",
    "EBQZaA",
    "EE0ftK",
    "TfjQgk",
    "BZMSC0",
    "LrXFSZ",
    "T438Ns",
    "rWFT1n",
    "TEV0OM",
    "HShz51",
    "4laXUj",
    "BWrfMO",
    "HQxvHc",
    "TfagXt",
    "4IyDcD",
    "B6ol1w",
    "HjSLy9",
    "B3hvyA",
    "4JtxV2",
    "TNYSdr",
    "4ojLhU",
    "B6SCXf",
    "Ha8Odd",
    "8i2YlC",
    "8TFZRv",
    "BvgufR",
    "BuVZB2",
    "BlRqzc",
    "LrTn0k",
    "LQrJtH",
    "B6Pvr3",
    "B6lq2I",
    "4hUkMB",
    "LmilPR",
    "MkCMxW",
    "BlRqzc",
    "LQ4hPt",
    "Ec9SWJ",
    "T438Ns",
    "BvghZy",
    "4hUkMB",
    "HAYnF0",
    "L8DPng",
    "HUUdcf",
    "LQTROh",
    "LmnFWz",
    "8bgL48",
    "HDSpMt",
    "HKGGSp",
    "H5dHjN",
    "EBQZaA",
    "EE0ftK",
    "LMAuJT",
  }
}
return whitelist
